name: iOS starter workflow

on:
  push:
    branches: [ "action" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          pod install --repo-update --clean-install --project-directory=/Desktop/Motto/
          
          # xcodebuild build -workspace Motto/SeSAC-Motto.xcworkspace -scheme SeSAC-Motto -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.4'
